pipeline {
    agent any

    environment {
        GITHUB_PAT = credentials('github-pat')  // ID de la credencial en Jenkins
    }

    stages {
        stage('Checkout Infra') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: 'main']],
                          userRemoteConfigs: [[url: 'https://github.com/Equipo4DevSecOps/devsecops-infra.git',
                                               credentialsId: 'github-pat']]])
            }
        }

        stage('Checkout App Code') {
            steps {
                sh 'git clone https://$GITHUB_PAT@github.com/Equipo4DevSecOps/todo-app.git || echo "Repo already exists"'
            }
        }

        stage('SAST') {
            steps {
                sh 'bash security/sast.sh'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml -i ansible/inventory.ini'
            }
        }
    }
}
