pipeline {
    agent any

    environment {
        GITHUB_PAT = credentials('github-pat')  // ID de la credencial en Jenkins
    }

    stages {
        stage('Checkout Infra') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: 'main']],
                          userRemoteConfigs: [[url: 'https://github.com/Equipo4DevSecOps/devsecops-infra.git',
                                               credentialsId: 'github-pat']]])
            }
        }

        stage('Checkout App Code') {
			steps {
				sh '''
				if [ -d "todo-app/.git" ]; then
					echo "Repo already exists, pulling latest changes"
					cd todo-app
					git reset --hard
					git clean -fd
					git pull origin main
					cd ..
				else
					git clone https://$GITHUB_PAT@github.com/Equipo4DevSecOps/todo-app.git
				fi
				'''
			}
		}

        stage('SAST') {
            steps {
                sh 'bash security/sast.sh'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml -i ansible/inventory.ini'
            }
        }
    }
}
